# Generated by Django 5.0 on 2023-12-17 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mobile', models.CharField(default='0123', max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_created_by', to='api.customuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user', to='api.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(blank=True, editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_created_by', to='api.customuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_user', to='api.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vehicle_no', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_user', to='api.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('datescheduled', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('extratime', models.TimeField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('isverfied', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_created_by', to='api.customuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_user', to='api.customuser')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_vehicle', to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_created_by', to='api.customuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_user', to='api.customuser')),
            ],
        ),
    ]
