# Generated by Django 5.0 on 2023-12-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='extratime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
