# Generated by Django 5.0 on 2023-12-12 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='vehicles',
            new_name='vehicle_id',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_user', to='api.customuser'),
        ),
    ]
